### ISSUE TITLE
`yaml/generate-string` doesn't seem to indent list items properly with `:block` flow-style and `:indent` options

### ISSUE THREAD

**Issue by samuelludwig** [babashka/babashka#1184]
**version**

v0.6.4

**platform**

WSL2 - Ubuntu 20.04.3 LTS (Focal Fossa)

**problem**

As far as I understand, in YAML, when you have a list that belongs to a given key (lets say we have the key `pets`, with a list of elements `dog` and `cat`), the children list items are indented relative to the indentation of the key. Our example should look like so:

```yaml
pets:
  - dog
  - cat
```

However, when I provide the datastructure I particularly believe should result in this format `{:pets ["dog" "cat"]}`, the result is:

```yaml
pets:
- dog
- cat
```

where the list items are not indented relative to the parent.

Likewise, `{:animal-types {:pets ["dog" "cat"]}}` results in:

```yaml
animal-types:
  pets:
  - dog
  - cat
```

It also appears that the typical `indent` and `indicator-indent` options don't seem to have any effect on the outputted string.

**repro**

GIVEN: `(yaml/generate-string {:animal-types {:pets ["dog" "cat"]}} :dumper-options {:flow-style :block})`
EXPECTED:
```yaml
animal-types:
  pets:
    - dog
    - cat
```

And from the `clj-commons/clj-yaml` repo:
GIVEN
```clojure
(yaml/generate-string some-data :dumper-options {:indent 6
                                                 :indicator-indent 3
                                                 :flow-style :block})
```
EXPECTED:
```yaml
todo:
   -  name: Fix issue
      responsible:
            name: Rita
```

**expected behavior**

Indentation to be applied uniformly to list children and key-value children.
